### ISSUE TITLE
[FR] Show timer in frames on screen. 

### ISSUE THREAD

**Issue by bigger0gamer** [AndreaJens/DigimonRumbleArenaTrainingTools#4]
Can just be the current value of the timer in memory, draw at the bottom center of the screen. That way, everything in the game can be counted in frames, not just the frames of moves. Ex: Counting the number of frames for stage hazards like when the hand claw for Recycling appears, how long it takes to set boxes down, etc.

**Comment by AndreaJens** [comment]
Added in [Release v1.4.1](https://github.com/AndreaJens/DigimonRumbleArenaTrainingTools/releases/tag/v1.4.1). It is shown if the numeric HP/Digi is shown.
