### ISSUE TITLE
[Bug] Digivolve/Super while using L3 menu. 

### ISSUE THREAD

**Issue by bigger0gamer** [AndreaJens/DigimonRumbleArenaTrainingTools#6]
The current keybindings can cause you to digivolve or do super while changing values. A couple solutions:

1) Change the value change keys to select and R3, as they don't correspond to any in game action. 
2) When L3 is pressed on a controller, have the other controller press start to pause the game, and use dpad to navigate the menu and change options, and unpause the game when L3 is pressed again. (Only the player that paused can control the pause menu.)

I know doing stuff in the background isn't really a bug, but I wasn't really sure what else to label it as :P

**Comment by AndreaJens** [comment]
I will leave L1/R1 L2/R2 to navigate the menu, but move the training menu to be synced with the pause menu. This feature is currently being tested.

**Comment by AndreaJens** [comment]
Fixed in [Release v1.4.1](https://github.com/AndreaJens/DigimonRumbleArenaTrainingTools/releases/tag/v1.4.1). The menu is now bound to Start.
