### ISSUE TITLE
[FR] Combos to include stun.

### ISSUE THREAD

**Issue by bigger0gamer** [AndreaJens/DigimonRumbleArenaTrainingTools#7]
Combos that end in stun don't currently count in the combo counter. Perhaps making the definition of combos be staying in any of the following states: hitstun, air juggle, knockdown, air knockdown, wake up, stun. Once the dummy state is not one of those, the combo ends.

**Comment by AndreaJens** [comment]
This should be already implemented, but I will check if it is by chance a bug. A combo is considered valid if the target doesn't go back to a Block or Idle stance, currently.

**Comment by AndreaJens** [comment]
Confirmed to be a bug. Fixing...

**Comment by AndreaJens** [comment]
Fixed in [Release v1.4.1](https://github.com/AndreaJens/DigimonRumbleArenaTrainingTools/releases/tag/v1.4.1).
