### ISSUE TITLE
[FR] Option for dummy to mash buttons while in stun state. 

### ISSUE THREAD

**Issue by bigger0gamer** [AndreaJens/DigimonRumbleArenaTrainingTools#9]
Would make for better practice for combos after a stun, and would let players test just how far opponents can be pushed before optimal mashing lets them escape a set up. Options for half speed or third speed mashing for a more realistic idea of what an actual player can mash out of would be awesome too.

I haven't tested what the optimal mash is yet, but likely hitting every button every other frame.

**Comment by AndreaJens** [comment]
Added this function to the master branch as of [this commit ](https://github.com/AndreaJens/DigimonRumbleArenaTrainingTools/commit/8804693b0d821e4ac83e66ec97bcba73abafc719).
